#include <windows.h>
#include <stdio.h>

void dump(unsigned int type, const char* name) {
    wchar_t buffer[32];
    wchar_t out[32];
    int i = 0;

    printf("unsigned short %s[0x10000] = {\n", name);
    for (;;) {
        if (i == 0x10000) break;
        for (int j = 0; j < 32; j++) {
            buffer[j] = i + j;
        }
        i += 32;

        GetStringTypeW(type, buffer, 32, out);
        printf("\t0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x,\n", out[0], out[1], out[2], out[3], out[4], out[5], out[6], out[7]);
        printf("\t0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x,\n", out[8], out[9], out[10], out[11], out[12], out[13], out[14], out[15]);
        printf("\t0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x,\n", out[16], out[17], out[18], out[19], out[20], out[21], out[22], out[23]);
        printf("\t0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x, 0x%x,\n", out[24], out[25], out[26], out[27], out[28], out[29], out[30], out[31]);
    }
    printf("};\n\n");
}

int main() {
    printf("// Generated by utils/dump_gstw_table.c\n");
    printf("// Do not edit it manually\n\n");
    
    dump(CT_CTYPE1, "gstw_ct1_table");
    dump(CT_CTYPE2, "gstw_ct2_table");
    dump(CT_CTYPE3, "gstw_ct3_table");
}